const actionTypes = {
  RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  CREATE_WIDGET_SUCCESS: 'CREATE_WIDGET_SUCCESS',
};

export default actionTypes;
