const actionTypes = {
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  RECOVER_PASSWORD_SUCCESS: 'RECOVER_PASSWORD_SUCCESS',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  CREATE_WIDGET_SUCCESS: 'CREATE_WIDGET_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export default actionTypes;
